user:
  name: "Zach S"
  experience: "Transported toxic chemicals at ACME"
  phone: "(123) 456-7890"
  github: "https://github.com/zacisyourmaster"
  linkedin: "https://linkedin.com/in/jzachs"
  email: "jzachsjobs@gmail.com"
  role: 'The Coyote'
  years_exp: 5
  industries: "Comic Hijinks"
  achievement: "Almost caught the Road Runner"
